In [3]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

Data Generation
===

In [4]:
num_samples, num_features = 3, 2

In [5]:
np.random.seed(10)
data = np.random.rand(num_samples, num_features)

Solution
===

In [6]:
print(data) #2 measures with each 3 values

[[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]]


In [43]:
x = data
y= np.mean(x, axis=0) 
z = np.std(x, axis=0)
y,z

(array([0.63449196, 0.33145083]), array([0.1113773 , 0.30664446]))

In [40]:
#standardizing: each dimension has zero mean and unit varianc

def standardize(x):
    ''' fill your code in here...
    '''
    centered_data = x - np.mean(x, axis=0)
    std_data = centered_data / np.std(centered_data, axis=0) # std(centered_data) = std(data)
    return std_data

std_data = standardize(data)
std_data

array([[ 1.228515  , -1.01322187],
       [-0.00757541,  1.36103242],
       [-1.2209396 , -0.34781055]])

In [11]:
print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[ 1.228515   -1.01322187]
 [-0.00757541  1.36103242]
 [-1.2209396  -0.34781055]] 

 [6.66133815e-16 5.55111512e-17] 

 [1. 1.]
